import {useEffect,useState} from 'react';import {useNavigate} from 'react-router-dom';import {sb,upload,useData,inr,PHONE} from './lib';
const empty={name:'',type_id:'',fabric:'',colour:'',price:'',description:'',in_stock:true,featured:false,images:[]};
export default function Admin(){const nav=useNavigate(),[ok,setOk]=useState(false),[tab,setTab]=useState('home');
useEffect(()=>{sb.auth.getUser().then(async({data})=>{const u=data.user;if(!u)return nav('/contact');const{data:a}=await sb.from('admins').select('user_id').eq('user_id',u.id);a?.length?setOk(true):nav('/contact')})},[]);
if(!ok)return <p className="p-20 text-center">Checking access…</p>;
return <div className="mx-auto max-w-6xl px-4 py-6"><div className="mb-6 flex flex-wrap items-center gap-2"><h1 className="mr-auto text-3xl">Admin panel</h1>{[['home','Dashboard'],['types','Types'],['sarees','Sarees'],['book','Pre-bookings']].map(([k,l])=><button key={k} onClick={()=>setTab(k)} className={`rounded-full px-4 py-1.5 ${tab===k?'bg-maroon text-ivory':'bg-blush text-maroon'}`}>{l}</button>)}<button className="px-3 text-sm underline" onClick={async()=>{await sb.auth.signOut();nav('/')}}>Log out</button></div>
{tab==='home'&&<Dash/>}{tab==='types'&&<Types/>}{tab==='sarees'&&<Sarees/>}{tab==='book'&&<Book/>}</div>}
function Dash(){const[c,setC]=useState({});useEffect(()=>{(async()=>{const n=async(t,f)=>{let q=sb.from(t).select('*',{count:'exact',head:true});if(f)q=q.eq(...f);return(await q).count};setC({Sarees:await n('sarees'),Types:await n('types'),'New pre-bookings':await n('prebookings',['status','new'])})})()},[]);
return <div className="grid gap-4 md:grid-cols-3">{Object.entries(c).map(([k,v])=><div key={k} className="rounded-2xl bg-white p-6 text-center shadow"><div className="font-head text-5xl text-maroon">{v??0}</div><div>{k}</div></div>)}</div>}
function Types(){const[l,load]=useData(()=>sb.from('types').select('*').order('name')),[name,setN]=useState(''),[f,setF]=useState(),[ed,setEd]=useState();
const save=async e=>{e.preventDefault();const cover=f?await upload('saree-images',f):ed?.cover_url;const row={name,cover_url:cover};ed?await sb.from('types').update(row).eq('id',ed.id):await sb.from('types').insert(row);setN('');setF();setEd();load()};
return <div><form onSubmit={save} className="mb-6 flex flex-wrap gap-2"><input required className="inp !w-60" placeholder="Type name" value={name} onChange={e=>setN(e.target.value)}/><input type="file" accept="image/*" onChange={e=>setF(e.target.files[0])}/><button className="btn">{ed?'Save changes':'Add type'}</button></form>
{(l||[]).map(t=><div key={t.id} className="mb-2 flex items-center gap-3 rounded-xl bg-white p-3">{t.cover_url&&<img src={t.cover_url} alt="" className="h-12 w-12 rounded object-cover"/>}<span className="mr-auto">{t.name}</span><button onClick={()=>{setEd(t);setN(t.name)}} className="text-peacock">Edit</button><button onClick={async()=>{confirm('Delete this type?')&&(await sb.from('types').delete().eq('id',t.id),load())}} className="text-red-600">Delete</button></div>)}</div>}
function Sarees(){const[l,load]=useData(()=>sb.from('sarees').select('*').order('created_at',{ascending:false})),[types]=useData(()=>sb.from('types').select('*')),[f,setF]=useState(null),[busy,setB]=useState(false);const on=k=>e=>setF({...f,[k]:e.target.type==='checkbox'?e.target.checked:e.target.value});
const add=async e=>{setB(true);try{const u=await Promise.all([...e.target.files].map(x=>upload('saree-images',x)));setF({...f,images:[...f.images,...u]})}catch(x){alert(x.message)}setB(false)};
const save=async e=>{e.preventDefault();const{id,created_at,...row}=f;row.price=Number(row.price)||0;row.type_id=row.type_id||null;const{error}=id?await sb.from('sarees').update(row).eq('id',id):await sb.from('sarees').insert(row);if(error)return alert(error.message);setF(null);load()};
if(f)return <form onSubmit={save} className="max-w-xl space-y-3"><input required className="inp" placeholder="Saree name" value={f.name} onChange={on('name')}/><select className="inp" value={f.type_id||''} onChange={on('type_id')}><option value="">Select type</option>{(types||[]).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><input className="inp" placeholder="Fabric" value={f.fabric||''} onChange={on('fabric')}/><input className="inp" placeholder="Colour" value={f.colour||''} onChange={on('colour')}/><input type="number" className="inp" placeholder="Price (₹)" value={f.price} onChange={on('price')}/><textarea className="inp" placeholder="Description" value={f.description||''} onChange={on('description')}/>
<label><input type="checkbox" checked={f.in_stock} onChange={on('in_stock')}/> In stock</label> <label className="ml-4"><input type="checkbox" checked={f.featured} onChange={on('featured')}/> Featured on home page</label>
<div><input type="file" accept="image/*" multiple onChange={add}/>{busy&&<span> Uploading…</span>}<div className="mt-2 flex flex-wrap gap-2">{f.images.map((u,i)=><div key={u} className="relative"><img src={u} alt="" className="h-24 w-20 rounded object-cover"/><button type="button" onClick={()=>setF({...f,images:f.images.filter(x=>x!==u)})} className="absolute right-0 top-0 rounded-full bg-white px-1.5">×</button>{i>0&&<button type="button" onClick={()=>setF({...f,images:[u,...f.images.filter(x=>x!==u)]})} className="absolute bottom-0 w-full bg-black/60 text-xs text-white">Make first</button>}</div>)}</div></div>
<div className="flex gap-2"><button className="btn">Save saree</button><button type="button" onClick={()=>setF(null)} className="px-4">Cancel</button></div></form>;
return <div><button className="btn mb-4" onClick={()=>setF(empty)}>Add saree</button>{(l||[]).map(s=><div key={s.id} className="mb-2 flex items-center gap-3 rounded-xl bg-white p-3"><img src={s.images?.[0]} alt="" className="h-14 w-11 rounded object-cover"/><span className="mr-auto">{s.name} · {inr(s.price)}</span><button onClick={()=>setF(s)} className="text-peacock">Edit</button><button onClick={async()=>{confirm('Delete this saree?')&&(await sb.from('sarees').delete().eq('id',s.id),load())}} className="text-red-600">Delete</button></div>)}</div>}
function Book(){const[l,load]=useData(()=>sb.from('prebookings').select('*').order('created_at',{ascending:false}));
return <div className="space-y-3">{(l||[]).map(b=><div key={b.id} className="flex flex-wrap gap-4 rounded-xl bg-white p-4"><img src={b.saree_image_url} alt="" className="h-28 w-22 rounded object-cover"/>{b.reference_image_url&&<a href={b.reference_image_url} target="_blank"><img src={b.reference_image_url} alt="Reference" className="h-28 rounded object-cover"/></a>}
<div className="min-w-48 flex-1 text-sm"><b className="text-base">{b.name}</b> · {b.saree_name}<br/>{b.phone} {b.email&&`· ${b.email}`}<br/>{b.city} {b.preferred_date&&`· wants by ${b.preferred_date}`}<br/>{b.message}<br/><a className="text-peacock" href={`tel:${b.phone}`}>Call</a> · <a className="text-peacock" target="_blank" href={`https://wa.me/${b.phone.replace(/\D/g,'').replace(/^(\d{10})$/,'91$1')}`}>WhatsApp</a></div>
<select value={b.status} onChange={async e=>{await sb.from('prebookings').update({status:e.target.value}).eq('id',b.id);load()}} className="inp !w-36 self-start">{['new','contacted','confirmed','cancelled'].map(s=><option key={s}>{s}</option>)}</select></div>)}{l?.length===0&&<p>No pre-bookings yet.</p>}</div>}
