import {useState} from 'react';import {Link,useParams,useNavigate} from 'react-router-dom';import {motion,AnimatePresence} from 'framer-motion';
import {sb,upload,useData,useWish,useLongPress,Reveal,Logo,inr,PHONE,ADDRESS} from './lib';
const Heart=({id})=>{const{ids,toggle}=useWish(),on=ids.includes(id);return <motion.button whileTap={{scale:1.5}} onClick={e=>{e.preventDefault();toggle(id)}} aria-label="Wishlist" className={`absolute right-3 top-3 grid h-9 w-9 place-items-center rounded-full bg-white/90 text-lg shadow ${on?'text-maroon':'text-neutral-400'}`}>{on?'♥':'♡'}</motion.button>};
const Card=({s,i=0})=><motion.div initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:(i%4)*.08}} whileHover={{y:-8}}>
<Link to={`/saree/${s.id}`} className="relative block overflow-hidden rounded-2xl bg-white shadow-md ring-1 ring-gold/30"><div className="aspect-[3/4] overflow-hidden bg-blush"><img loading="lazy" src={s.images?.[0]} alt={s.name} className="h-full w-full object-cover transition duration-700 hover:scale-110"/></div>
<Heart id={s.id}/><div className="p-4"><h3 className="text-xl font-semibold">{s.name}</h3><p className="text-sm text-neutral-500">{s.fabric}</p><p className="mt-1 font-medium text-peacock">{inr(s.price)}{!s.in_stock&&<span className="ml-2 text-xs text-neutral-400">Out of stock</span>}</p></div></Link></motion.div>;
const Grid=({list})=>!list?<p className="p-10 text-center">Loading…</p>:!list.length?<p className="p-10 text-center">No sarees yet. Check back soon.</p>:<div className="grid grid-cols-2 gap-4 md:grid-cols-4">{list.map((s,i)=><Card key={s.id} s={s} i={i}/>)}</div>;
const Title=({children,sub})=><div className="py-10 text-center"><h1 className="text-4xl font-bold md:text-5xl">{children}</h1>{sub&&<p className="mt-2 text-neutral-500">{sub}</p>}<div className="border-pat mx-auto mt-4 w-40 rounded"/></div>;
export function Home(){const[feat]=useData(()=>sb.from('sarees').select('*').eq('featured',true).limit(8)),[types]=useData(()=>sb.from('types').select('*'));const name='Sudha Sarees'.split('');
return <>
<section className="relative grid min-h-[88vh] place-items-center overflow-hidden bg-gradient-to-br from-maroon via-[#9b2a4c] to-[#4a1024] px-4 text-center">
{[...Array(14)].map((_,i)=><motion.span key={i} className="absolute text-gold/70" style={{left:`${(i*7+5)%100}%`,top:`${(i*13)%90}%`}} animate={{y:[0,-30,0],rotate:[0,180,360],opacity:[.2,.9,.2]}} transition={{duration:5+i%4,repeat:Infinity,delay:i*.3}}>✦</motion.span>)}
<div className="relative"><div className="mx-auto w-fit"><Logo size={120} draw/></div>
<h1 className="mt-5 text-6xl font-bold !text-gold md:text-8xl">{name.map((c,i)=><motion.span key={i} className="inline-block" initial={{opacity:0,y:40,rotate:8}} animate={{opacity:1,y:0,rotate:0}} transition={{delay:1.2+i*.07}}>{c===' '?'\u00A0':c}</motion.span>)}</h1>
<motion.p initial={{opacity:0}} animate={{opacity:1}} transition={{delay:2.4}} className="mt-3 text-lg text-blush">Timeless sarees, woven with tradition. Rayachoty</motion.p>
<motion.div initial={{opacity:0,scale:.8}} animate={{opacity:1,scale:1}} transition={{delay:2.8}} className="mt-8 flex justify-center gap-3"><Link to="/sarees" className="btn !bg-gold !text-maroon">Explore sarees</Link><Link to="/contact" className="btn">Visit our shop</Link></motion.div></div></section>
<div className="overflow-hidden bg-blush py-3 text-maroon"><div className="mq flex w-max gap-10 font-head text-2xl">{[...(types||[]),...(types||[]),...(types||[]),...(types||[])].map((t,i)=><span key={i}>✦ {t.name}</span>)}</div></div>
<section className="mx-auto max-w-6xl px-4"><Title sub="Hand-picked for you">Featured sarees</Title><Grid list={feat}/></section>
<section className="mx-auto max-w-6xl px-4"><Title>Shop by type</Title><div className="grid grid-cols-2 gap-4 md:grid-cols-3">{(types||[]).map((t,i)=><Reveal key={t.id} d={i*.06}><TypeTile t={t}/></Reveal>)}</div></section>
<section className="mx-auto mt-16 grid max-w-6xl gap-5 px-4 md:grid-cols-3">{[['Authentic weaves','Silk and cotton sourced directly from weavers.'],['Pre-book your saree','Reserve a saree online and we will call you to confirm.'],['Visit our store','Opposite New Police Station, Kadiri Road, Rayachoty.']].map(([a,b],i)=><Reveal key={a} d={i*.15}><div className="rounded-2xl border border-gold/40 bg-white p-6 text-center"><h3 className="text-2xl">{a}</h3><p className="mt-2 text-neutral-600">{b}</p></div></Reveal>)}</section></>}
const TypeTile=({t})=><Link to={`/sarees/${t.id}`} className="group relative block aspect-[4/3] overflow-hidden rounded-2xl bg-gradient-to-br from-maroon to-gold shadow-md">{t.cover_url&&<img loading="lazy" src={t.cover_url} alt={t.name} className="absolute inset-0 h-full w-full object-cover transition duration-700 group-hover:scale-110"/>}<div className="absolute inset-0 grid place-items-end bg-gradient-to-t from-black/60 to-transparent p-4"><span className="font-head text-2xl text-white">{t.name}</span></div></Link>;
export function Types(){const[t]=useData(()=>sb.from('types').select('*').order('name'));return <div className="mx-auto max-w-6xl px-4"><Title sub="Choose a type to see the collection">Our sarees</Title><div className="grid grid-cols-2 gap-4 md:grid-cols-3">{(t||[]).map((x,i)=><Reveal key={x.id} d={i*.06}><TypeTile t={x}/></Reveal>)}</div></div>}
export function TypePage(){const{typeId}=useParams(),[sort,setSort]=useState('new'),[t]=useData(()=>sb.from('types').select('*').eq('id',typeId),[typeId]),[l]=useData(()=>sb.from('sarees').select('*').eq('type_id',typeId),[typeId]);
const sorted=l&&[...l].sort((a,b)=>sort==='lo'?a.price-b.price:sort==='hi'?b.price-a.price:0);
return <div className="mx-auto max-w-6xl px-4"><Title>{t?.[0]?.name||'Sarees'}</Title><div className="mb-4 text-right"><select className="inp !w-auto" value={sort} onChange={e=>setSort(e.target.value)}><option value="new">Newest</option><option value="lo">Price: low to high</option><option value="hi">Price: high to low</option></select></div><Grid list={sorted}/></div>}
export function Detail(){const{id}=useParams(),[r]=useData(()=>sb.from('sarees').select('*').eq('id',id),[id]),[i,setI]=useState(0),[zoom,setZ]=useState(false),[book,setBook]=useState(false),s=r?.[0];
if(!r)return <p className="p-20 text-center">Loading…</p>;if(!s)return <p className="p-20 text-center">Saree not found.</p>;const im=s.images||[];
return <div className="mx-auto grid max-w-6xl gap-8 px-4 py-8 md:grid-cols-2"><div><div className="relative overflow-hidden rounded-2xl bg-blush"><AnimatePresence mode="wait"><motion.img key={i} src={im[i]} alt={s.name} onClick={()=>setZ(true)} drag="x" dragConstraints={{left:0,right:0}} onDragEnd={(_,o)=>{if(o.offset.x<-60)setI((i+1)%im.length);if(o.offset.x>60)setI((i-1+im.length)%im.length)}} initial={{opacity:0,scale:1.05}} animate={{opacity:1,scale:1}} exit={{opacity:0}} className="aspect-[3/4] w-full cursor-zoom-in object-cover"/></AnimatePresence><Heart id={s.id}/></div>
<div className="mt-3 flex gap-2 overflow-x-auto">{im.map((u,k)=><img key={k} src={u} onClick={()=>setI(k)} alt="" className={`h-20 w-16 cursor-pointer rounded-lg object-cover ring-2 transition ${k===i?'ring-maroon':'ring-transparent opacity-70'}`}/>)}</div></div>
<div><h1 className="text-4xl font-bold">{s.name}</h1><p className="mt-2 text-3xl text-peacock">{inr(s.price)}</p><dl className="mt-4 space-y-1 text-neutral-700"><div>Fabric: {s.fabric||'-'}</div><div>Colour: {s.colour||'-'}</div><div>{s.in_stock?'In stock':'Out of stock (pre-book to reserve)'}</div></dl><p className="mt-4 leading-relaxed text-neutral-600">{s.description}</p><button className="btn mt-6" onClick={()=>setBook(true)}>Pre-book this saree</button></div>
<AnimatePresence>{zoom&&<motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setZ(false)} className="fixed inset-0 z-50 grid cursor-zoom-out place-items-center bg-black/90 p-4"><img src={im[i]} alt={s.name} className="max-h-full max-w-full"/></motion.div>}{book&&<PreBook s={s} close={()=>setBook(false)}/>}</AnimatePresence></div>}
function PreBook({s,close}){const[f,setF]=useState({name:'',phone:'',email:'',city:'',preferred_date:'',message:''}),[file,setFile]=useState(),[st,setSt]=useState('idle'),[err,setErr]=useState('');const on=k=>e=>setF({...f,[k]:e.target.value});
const go=async e=>{e.preventDefault();setSt('busy');try{const ref=file?await upload('prebook-refs',file):null;const{error}=await sb.from('prebookings').insert({...f,preferred_date:f.preferred_date||null,saree_id:s.id,saree_name:s.name,saree_image_url:s.images?.[0],reference_image_url:ref});if(error)throw error;setSt('done')}catch(x){setErr(x.message);setSt('idle')}};
return <motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-black/60 p-4"><motion.div initial={{y:60,scale:.95}} animate={{y:0,scale:1}} className="w-full max-w-md rounded-2xl bg-ivory p-6">
{st==='done'?<div className="py-8 text-center"><motion.div initial={{scale:0}} animate={{scale:1}} transition={{type:'spring'}} className="mx-auto grid h-20 w-20 place-items-center rounded-full bg-peacock text-4xl text-white">✓</motion.div><h2 className="mt-4 text-3xl">Pre-booking received</h2><p className="mt-2">We will call you on {f.phone} to confirm.</p><button className="btn mt-5" onClick={close}>Close</button></div>:
<form onSubmit={go} className="space-y-3"><div className="flex items-center gap-3"><img src={s.images?.[0]} alt="" className="h-16 w-12 rounded object-cover"/><h2 className="text-2xl">Pre-book: {s.name}</h2></div>
<input required className="inp" placeholder="Your name" value={f.name} onChange={on('name')}/><input required type="tel" className="inp" placeholder="Phone number" value={f.phone} onChange={on('phone')}/><input type="email" className="inp" placeholder="Email (optional)" value={f.email} onChange={on('email')}/><input className="inp" placeholder="City / address" value={f.city} onChange={on('city')}/><input type="date" className="inp" value={f.preferred_date} onChange={on('preferred_date')}/><textarea className="inp" placeholder="Message" value={f.message} onChange={on('message')}/>
<label className="block text-sm">Reference photo (optional)<input type="file" accept="image/*" className="mt-1 block" onChange={e=>setFile(e.target.files[0])}/></label>{err&&<p className="text-sm text-red-600">{err}</p>}
<div className="flex gap-2"><button disabled={st==='busy'} className="btn flex-1">{st==='busy'?'Sending…':'Send pre-booking'}</button><button type="button" onClick={close} className="rounded-full px-4 text-maroon">Cancel</button></div></form>}</motion.div></motion.div>}
export function Wishlist(){const{ids}=useWish(),[l]=useData(()=>ids.length?sb.from('sarees').select('*').in('id',ids):Promise.resolve({data:[]}),[ids.join()]);return <div className="mx-auto max-w-6xl px-4"><Title sub="Sarees you have saved">Your wishlist</Title><Grid list={l}/></div>}
export function About(){return <div className="mx-auto max-w-4xl px-4"><Title>Our story</Title>{[['A family tradition in Rayachoty','Sudha Sarees began with one belief: every woman deserves a saree that feels like her own. We bring silk, cotton and bridal weaves from trusted weavers to Annamayya district.'],['Quality you can feel','Each saree is checked by hand for weave, zari and finish before it reaches our shelves.'],['Personal service','Pre-book online, visit the shop, and we will help you choose for weddings, festivals and everyday wear.']].map(([a,b],i)=><Reveal key={a} d={.1}><div className={`my-6 flex gap-4 rounded-2xl border border-gold/40 bg-white p-6 ${i%2?'md:ml-16':'md:mr-16'}`}><Logo size={44}/><div><h2 className="text-2xl">{a}</h2><p className="mt-1 text-neutral-600">{b}</p></div></div></Reveal>)}</div>}
export function Contact(){const nav=useNavigate(),[login,setLogin]=useState(false),[m,setM]=useState({n:'',t:''}),lp=useLongPress(()=>setLogin(true));
return <div className="mx-auto max-w-6xl px-4"><Title>Visit us</Title><div className="grid gap-8 md:grid-cols-2"><div className="space-y-4"><p className="text-lg">{ADDRESS}</p><a className="btn inline-block" href={`tel:+${PHONE}`}>Call us</a> <a className="btn inline-block !bg-peacock" href={`https://wa.me/${PHONE}`}>WhatsApp</a>
<form className="space-y-3 pt-4" onSubmit={e=>{e.preventDefault();open(`https://wa.me/${PHONE}?text=${encodeURIComponent(`Hi, I am ${m.n}. ${m.t}`)}`)}}><input required className="inp" placeholder="Your name" value={m.n} onChange={e=>setM({...m,n:e.target.value})}/><textarea required className="inp" placeholder="Your message" value={m.t} onChange={e=>setM({...m,t:e.target.value})}/><button className="btn select-none" {...lp}>Send message</button></form></div>
<iframe title="Map" loading="lazy" className="h-96 w-full rounded-2xl border-0" src={`https://maps.google.com/maps?q=${encodeURIComponent(ADDRESS)}&output=embed`}/></div>{login&&<AdminLogin close={()=>setLogin(false)} ok={()=>nav('/admin')}/>}</div>}
function AdminLogin({close,ok}){const[e,setE]=useState(''),[p,setP]=useState(''),[er,setEr]=useState('');
const go=async x=>{x.preventDefault();const{data,error}=await sb.auth.signInWithPassword({email:e,password:p});if(error)return setEr('Wrong email or password.');const{data:a}=await sb.from('admins').select('user_id').eq('user_id',data.user.id);if(!a?.length){await sb.auth.signOut();return setEr('This account is not an admin.')}ok()};
return <div className="fixed inset-0 z-50 grid place-items-center bg-black/60 p-4"><motion.form initial={{scale:.9,opacity:0}} animate={{scale:1,opacity:1}} onSubmit={go} className="w-full max-w-sm space-y-3 rounded-2xl bg-ivory p-6"><h2 className="text-3xl">Admin login</h2><input required type="email" className="inp" placeholder="Email" value={e} onChange={x=>setE(x.target.value)}/><input required type="password" className="inp" placeholder="Password" value={p} onChange={x=>setP(x.target.value)}/>{er&&<p className="text-sm text-red-600">{er}</p>}<div className="flex gap-2"><button className="btn flex-1">Log in</button><button type="button" onClick={close} className="px-4 text-maroon">Cancel</button></div></motion.form></div>}
